[theme]
primaryColor = "#FF4B4B"         # màu nút chính (Predict button)
backgroundColor = "#FFFFFF"      # màu nền chính
secondaryBackgroundColor = "#D6EAF8"  # sidebar nền xanh nhạt
textColor = "#000000"            # màu chữ
font = "sans serif"
